
name: "Gradle Package"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  

jobs:
  job1:

    runs-on: macOS-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

   # - name: Grant execute permission for Gradle wrapper
   #   run: chmod +x gradlew

    - name: Compile
        run: gradle build -x test
     # run: ./gradlew compileJava

    - name: Run Tests
        run: gradle test
     # run: ./gradlew test

    - name: Code Review (Static Analysis)
        run: gradle check
     # run: ./gradlew check

    - name: Package JAR
        run: gradle jar
     # run: ./gradlew build

    